spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgresql
##    url: jdbc:postgresql://10.178.0.10:5432/postgresql
#    username: postgresql
#    password: postgrespassword
#  jpa:
#    show-sql: false
#    hibernate:
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#      ddl-auto: update
  rabbitmq:
#    host: localhost
    host: 10.178.0.11
    username: guest
    password: guest
    port: 5672
  data:
    elasticsearch:
      hosts: 10.178.0.12,10.178.0.13,10.146.0.2,10.146.0.3
      port: 9200
# for local test
#server:
#  port: 8081
