spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/postgresql
    url: jdbc:postgresql://10.178.0.10:5432/postgresql
    username: postgresql
    password: postgrespassword
  jpa:
    show-sql: false
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
  rabbitmq:
    host: 10.178.0.11
    username: guest
    password: guest
    port: 5672
# for local test
#server:
#  port: 8081
